version: '3.8'

services:
  qribot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qribot
    restart: unless-stopped
    # 也可以使用 .env 文件
    env_file:
      - .env.prod
    
    # 数据持久化 (如果需要)
    volumes:
      - ./.env.prod:/app/.env.prod
      - ./plugins/justice/prompts/:/app/plugins/justice/prompts/
      - ./logs:/app/logs
    # 网络配置 (如果需要与其他服务通信)
    # networks:
    #   - bot-network

# networks:
#   bot-network:
#     driver: bridge
